### ISSUE TITLE
Doc-Get Quarterly Office Expenses by Category for a Specific House Member

### ISSUE THREAD

**Issue by DavytJ** [propublica/campaign-finance-api-docs#1]
I think there are inconsistencies between the request and the documentation in:
https://projects.propublica.org/api-docs/congress-api/members/#get-quarterly-office-expenses-by-category-for-a-specific-house-member
Compare: http request vs Example Call
And look at 
https://projects.propublica.org/api-docs/congress-api/members/#get-quarterly-office-expenses-by-a-specific-house-member
if I try with https://api.propublica.org/congress/v1/members/A000374/office_expenses/category/travel.json" the API returns me an error: "Please specify a number between 1 and 4 for the quarter"

**Comment by dwillis** [comment]
Hi @DavytJ - I'm going to move this to the [Congress API issues](https://github.com/propublica/congress-api-docs/issues/210)

**Comment by DavytJ** [comment]
ok

2018-06-12 11:03 GMT-03:00 Derek Willis <notifications@github.com>:
