### ISSUE TITLE
in Get Recently Added Candidates some cycles get error status

### ISSUE THREAD

**Issue by DavytJ** [propublica/campaign-finance-api-docs#2]
I am not sure it is an issue, but I'm trying to use Get Recently Added Candidates endpoint (GET https://api.propublica.org/campaign-finance/v1/{cycle}/candidates/new) and I try with different cycles largest than 1996 and return me an error and the following message: "Cycle must be even-numbered year between 1996 and 2018". Years that don't return an error are: 2010, 2012, 2014, 2016 and 2018, the rest of possible years return the error.
Thanks

**Comment by dwillis** [comment]
Thanks, @DavytJ - we need to update the docs to clarify that this response is available for cycles >= 2010.

**Comment by dwillis** [comment]
This is done.

**Comment by DavytJ** [comment]
thanks!
