### ISSUE TITLE
in Search for Candidates some cycles get error status

### ISSUE THREAD

**Issue by DavytJ** [propublica/campaign-finance-api-docs#3]
I use the following HTTP Request: GET https://api.propublica.org/campaign-finance/v1/{cycle}/candidates/search.
I put the Name 'Wilson' as the example.
Give me:
$status
[1] "ERROR"
$copyright
[1] "Copyright (c) 2018 ProPublica Inc. All Rights Reserved."
$errors
[1] "Cycle must be even-numbered year between 1996 and 2018"

For 1997, 1999, 2001, 2003, 2005, 2007, 2009, 2011 and 2013.

Thanks

**Comment by dwillis** [comment]
Hi @DavytJ those years you mention are not even-numbered years, so an error is the correct response.

**Comment by DavytJ** [comment]
ok
