### ISSUE TITLE
Get Recent Late Contributions by Date: difference between HTTP Request vs Example Call

### ISSUE THREAD

**Issue by DavytJ** [propublica/campaign-finance-api-docs#4]
In https://projects.propublica.org/api-docs/campaign-finance/candidates/#get-recent-late-contributions-by-date there are a difference between HTTP Request and Example Call.

HTTP Request
GET http://api.propublica.org/campaign-finance/v1/{cycle}/contributions/48hour/{year}/{month}/{day}

Example Call
curl "https://api.propublica.org/campaign-finance/v1/2016/candidates/P60005915.json"
  -H "X-API-Key: PROPUBLICA_API_KEY"

**Comment by dwillis** [comment]
Thanks, @DavytJ! This is fixed now.
