### ISSUE TITLE
Get Recent Late Contributions by Date: errror in match cycle

### ISSUE THREAD

**Issue by DavytJ** [propublica/campaign-finance-api-docs#6]
I try to get data from https://api.propublica.org/campaign-finance/v1/{cycle}/contributions/48hour/{year}/{month}/{day} where
cycle = 2018
year = 2018
month = 06
day = 02
and also
cycle = 2016
year = 2016
month = 09
day = 07
but return a status error, with message =  "Specified year does not match cycle"

**Comment by dwillis** [comment]
@DavytJ thanks - we'll fix this afternoon.

**Comment by dwillis** [comment]
@DavytJ This should be fixed now.

**Comment by DavytJ** [comment]
Yes!
